### ISSUE TITLE
Uncatchable Exception from rrule

### ISSUE THREAD

**Issue by Apollon77** [jens-maus/node-ical#14]
we got a Sentry crash report:

https://sentry.iobroker.net/share/issue/d68908f6a8824381ab4e390108378841/

```
Error: Unknown RRULE property 'RRULE'
  File "/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts", line 98, col 15, in null.<anonymous>
  ?, in Array.forEach
  File "/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts", line 56, col 9, in parseRrule
  File "/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts", line 42, col 14, in parseLine
  ?, in Array.map
  File "/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts", line 7, col 41, in Function.parseString
  File "/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/rrule.ts", line 127, col 28, in Function.RRule.fromString
  File "/opt/iobroker/node_modules/node-ical/ical.js", line 415, col 30, in Object.END
    curr.rrule = rrule.fromString(rule);
  File "/opt/iobroker/node_modules/node-ical/ical.js", line 452, col 39, in Object.handleObject
    return self.objectHandlers[name](val, params, ctx, stack, line);
  File "/opt/iobroker/node_modules/node-ical/ical.js", line 499, col 18, in Object.parseLines
    ctx = self.handleObject(name, value, params, ctx, stack, l) || {};
```

in fact when I understood correct then https://github.com/jens-maus/node-ical/blob/master/ical.js#L415 can throw an exception ... this should be catched because of the "setImmediate" processing that exception is uncatchable else

**Comment by Apollon77** [comment]
@jens-maus Any chance to take a look?

**Comment by jens-maus** [comment]
Sorry, bit to me this looks like an issue in rrule which I don't have any idea why it throws these exceptions...

**Comment by Apollon77** [comment]
Lets say it that way: "why they are thrown" is one case", but if we say "they are valid" then we should get a way to catch  them - and  because of the setImmediate usage they are in fact not catchable from outside :-( This should be changed.

**Comment by jens-maus** [comment]
Sorry, don‘t have currently time to investigate+fix. Feel free to submit a PR!

**Comment by Apollon77** [comment]
The main question is what to return uf rrule iwere not able to be parsed, set to null? this would be easy. The second option is to somehow incudean eventemitter and emit an error event, but this is a bigger thing

**Comment by sdetweil** [comment]
is there any chance u know what the cal entry looked like? 

I have been debugging one like this, node-ical ignores, expected is   keyword:
this is keyword= and no 'colon' found

RRULE=RRULE;X-EVOLUTION-ENDDATE=20080828T130000Z:FREQ=WEEKLY;COUNT=4;BYDAY=TH

**Comment by sdetweil** [comment]
@Apollon77 I would set the rrule to null

**Comment by jens-maus** [comment]
mee too. So go ahead and submit a PR if you want...

**Comment by Apollon77** [comment]
> @Apollon77 I would set the rrule to null

I agree, most likely best way

**Comment by runely** [comment]
I got this exception today as well, using node-ical v0.12.3:

```javascript
Error: Unknown RRULE property 'RRULE'
    at /node_modules/rrule/dist/es5/rrule.js:1191:23
    at Array.forEach (<anonymous>)
    at parseRrule (/node_modules/rrule/dist/es5/rrule.js:1149:11)
    at parseLine (/node_modules/rrule/dist/es5/rrule.js:1138:20)
    at Array.map (<anonymous>)
    at Function.parseString (/node_modules/rrule/dist/es5/rrule.js:1110:41)
    at Function.RRule.fromString (/node_modules/rrule/dist/es5/rrule.js:2139:32)
    at Object.END (/node_modules/node-ical/ical.js:476:30)
    at Object.handleObject (/node_modules/node-ical/ical.js:514:39)
    at Object.parseLines (/node_modules/node-ical/ical.js:568:18)
```

I could recreate this exception with my own calendar by setting the RRULE property to `RRULE:RRULE=AnythingRandom:FREQ=WEEKLY;UNTIL=20211210T163500Z`.

Any fix near by?

**Comment by sdetweil** [comment]
great, I have recreated that.. let me see

**Comment by sdetweil** [comment]
just submitted pr to fix this..

**Comment by sdetweil** [comment]
@runely  >using node-ical v0.12.3

I only see 0.12.2 (in package.json)
i see 0.12.3 is published

**Comment by Apollon77** [comment]
@jens-maus I update ical adapter from iobroker tomorrow

**Comment by runely** [comment]
I'm still seeing this exception on v0.12.4. However it seems to be fixed for this syntax `RRULE:RRULE=AnythingRandom:FREQ=WEEKLY;UNTIL=20211210T163500Z` so it's beeing triggered on some other syntax as well.

Unfortunately i do not have an example at this time.

**Comment by sdetweil** [comment]
@runely the fix in .4 is RRULE=

if u can get to the node-ical/ical.js file
change the two tests from RRULE= to RRULE
to remove any Embedded RRULE

**Comment by sdetweil** [comment]
also if u have access to the log for this app, u could log the syntax of the embedded rrule for doc purposes as part of the short term patch. 

then we could review it too
like this
```
          // If the rule  includess the RRULE= clause remove it
          if (rule.includes('RRULE')) {   // this line changed
            console.log('embedded RRULE detected='+rule);  // this line added
            // Make an array
            const x = [];
            // Loop thru the parts of the rule
            for (const c of rule.split(';')) {
              // If its NOT the bad clause
              if (!c.includes('RRULE')) {   // this line changed
                // Save it
                x.push(c);
              }
            }
            // Reconstruct the rule

            rule = x.join(';');
          }
```

**Comment by jens-maus** [comment]
could we nit simply catch these kind of exceptions via a try{}catch{} statement rather than trying to remove the RRULE= stuff?

**Comment by runely** [comment]
I'm using node-ical in the Homey app [IcalCalendar](https://github.com/runely/calendar-homey). The exceptions i get is from other peoples Homey's and don't include anything other than just the exception thrown. No way to identify the user.

Giving us the opportunity to catch these exceptions in a try/catch would be desirable. I have a try/catch around the `ical.async.fromURL` call but it still can't catch it

**Comment by sdetweil** [comment]
@jens-maus  they don't seem to catch with try/catch...  

@runely   as I said, if u can get access to the node-ical folder under the app, we could capture the invalid RRULE string
we don't care about the user or the rest of the vevent..  
and as I proposed changing the bypass to more aggressive 'RRULE' vs 'RRULE='     basically something is throwing in an extra RRULE IN the RRULE string and RRULE  library is the one barfing

**Comment by sdetweil** [comment]
I posted a PR that does the above..
