### ISSUE TITLE
npm audit report warning

### ISSUE THREAD

**Issue by hkjeffchan** [jens-maus/node-ical#288]
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
Will install node-ical@0.13.0, which is a breaking change
node_modules/node-ical/node_modules/axios
  node-ical  >=0.14.0
  Depends on vulnerable versions of axios
  node_modules/node-ical

2 moderate severity vulnerabilities

Would you please pump the axios dependency and release a new version? Thanks.

**Comment by jens-maus** [comment]
should be fixed with 0.17.0
