### ISSUE TITLE
Missing Typings result in TS Compile Issues with stricter options (TS7008)

### ISSUE THREAD

**Issue by theimo1221** [jens-maus/node-ical#313]
Hello team,

these 2 lines prevent me from updating my TS project to node-ical V18 as some TS strict options doesn't allow implicit anys.
https://github.com/jens-maus/node-ical/blob/9985f8d0bcc10d1c67bee9a2bf9ca08293eed488/node-ical.d.ts#L89

https://github.com/jens-maus/node-ical/blob/9985f8d0bcc10d1c67bee9a2bf9ca08293eed488/node-ical.d.ts#L94

**Comment by jens-maus** [comment]
done by #327
