### ISSUE TITLE
pump axios dependency (npm audit report warning)

### ISSUE THREAD

**Issue by hkjeffchan** [jens-maus/node-ical#328]
2 high severity vulnerabilities were detected because of this. Thanks.

axios  >=1.3.2
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
fix available via `npm audit fix --force`
Will install axios@1.3.1, which is a breaking change
node_modules/axios
node_modules/node-ical/node_modules/axios
  node-ical  >=0.16.0
  Depends on vulnerable versions of axios
  node_modules/node-ical

2 high severity vulnerabilities

**Comment by jens-maus** [comment]
done by #330

**Comment by hkjeffchan** [comment]
@jens-maus Possible to release a new version (0.18.1) to npm for all the dependency pump?
