### ISSUE TITLE
If timezone is not in lookup, it causes parse error

### ISSUE THREAD

**Issue by jkschoen** [jens-maus/node-ical#46]
I actually ran into the issue when setting up magic mirror, but on my work outlook account, I published an ics so I could pull it in to the magic mirror dashboard. For some reason I had some past meetings that actually had "strange" timezones, that looked like `Central Standard Time 1`. No idea why, or how they got there. Most were sent from other people. 

Issue is when parsing it fails as a whole because of these meetings. I am not sure what the correct solution would be, returning a null timezone maybe, so it does not fail to parse altogether. My gut says there should be someway to continue parsing when it is actually just an issue with the timezone not being in the lookup.

If you have a way you would like this done, I am even willing to contribute the code and open a PR. I just want to make sure it is a solution you are good with first.

**Comment by sdetweil** [comment]
do u know what node-ical version you were using? this was a bug in 0.12.1, fixed in 12.2

**Comment by jens-maus** [comment]
should be indeed fixed already in 0.12.2
