### ISSUE TITLE
"Error: Invalid URI" thrown

### ISSUE THREAD

**Issue by runely** [jens-maus/node-ical#55]
I get an error in Sentry when a user has entered an URI without **http://** or **https://**. This same URL entered in Chrome (without http:// or https://) works.

Assuming the url to be *http://* might be one way to go?

![image](https://user-images.githubusercontent.com/25814673/100596486-8043b380-32fc-11eb-98d8-e7dfc0ccb36c.png)

**Comment by jens-maus** [comment]
Sorry, but the URI protocol definition (`http://`, `https://`) is required for the full URL. So tell your users to actually use a proper and complete URL and don't expect this nodejs library to add it for these unsupported cases. So sorry, but I don't see why we should change here something. The using app which uses node-ical should ensure the URL is correct and complete.
