### ISSUE TITLE
Server timezone enforced on all day events

### ISSUE THREAD

**Issue by scmunro** [jens-maus/node-ical#68]
When an all-day event is created in Google Calendar the start and end times are formatted as follows in the ics file:

`DTSTART;VALUE=DATE:20201225
DTEND;VALUE=DATE:20201226`

My node server is on UTC time so when this event is parsed the following is returned:

`start: "2020-12-25T00:00:00.000Z",
...
end: "2020-12-26T00:00:00.000Z",`

It is not possible to tell from this if the event is intended to be a timezone agnostic all-day event or a 24-hour event that just happens to start at 00:00 UTC.

I can hardcode an ugly fix in my app for my needs but curious if there is any other option?

**Comment by runely** [comment]
In the event object returned from node-ical, there's also a property called `datetype`.
This property is set to `date` when the event is a whole day event.

```javascript
{
    "type": "VEVENT",
    "params": [],
    "start": "2020-12-26T23:00:00.000Z",
    "datetype": "date",
    "end": "2020-12-27T23:00:00.000Z",
    "dtstamp": "2020-12-26T16:32:41.000Z",
    "uid": "removed@google.com",
    "created": "2020-12-26T16:31:30.000Z",
    "description": "",
    "lastmodified": "2020-12-26T16:31:30.000Z",
    "location": "",
    "sequence": "0",
    "status": "CONFIRMED",
    "summary": "Whole day 2",
    "transparency": "TRANSPARENT"
 }
```

**Comment by scmunro** [comment]
Ah, great. Thanks!
