### ISSUE TITLE
request package is deprecated

### ISSUE THREAD

**Issue by khassel** [jens-maus/node-ical#91]
see https://github.com/request/request

We are currently replacing `request` with `node-fetch` in the [magicmirror project](https://github.com/MichMich/MagicMirror/issues/2468).

`node-ical` is the only core dependency which is still using `request`, so we would be happy to get rid of this package.

Switching `node-ical` to `node-fetch` is no technical problem (could provide a PR), but the options in the `fromURL` function would change from request-options to node-fetch-options which would be a breaking change for the clients using this function.

Possible solutions:

1.  a new major release with breaking changes
2.  adding a new package `node-ical-core` with core-funtionality without the `fromURL` function and let `node-ical` use this as dependency. So we could use `node-ical-core` directly and/or create a third package `node-ical-fetch` which uses `node-fetch` in `fromURL`

Solution 2 is my favorite, what do you think about this?

**Comment by jens-maus** [comment]
I would prefer solution 1 to not overcomplicate things here and confuse users with two or more different package with no actual benefit compared to each other. So please provide a PR accordingly and I will the review it and consider bumping the major version to distinguish the breaking change.
